name: RockPaperScissors
author: Dartanman
main: me.dartanman.rockpaperscissors.RockPaperScissors
version: 0.0.3
api-version: 1.19
commands:
  rockpaperscissors:
    description: Rock, Paper, Scissors!
    usage: /<command>
    aliases: [rockpaperscissor, rps]